---

- name: "Install HTTPd and security modules"
  yum: name="httpd,mod_ssl,mod_security" state=present

- name: "Copy hardening configuration files"
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/httpd/conf.d/{{ item }}.conf"
    owner: root
    group: apache
    mode: 0640
  with_items:
    - ssl_custom
    - headers_custom
    - server_custom
  notify:
    - "restart httpd"

- name: "Enable HTTP daemon"
  service: name=httpd enabled=yes
